project_id = "rppbvrgxrafhacttmiqt"

[functions.preview-transactional-email]
verify_jwt = false

[functions.send-lead-contact-notification]
verify_jwt = true

[functions.send-bpo-contact-notification]
verify_jwt = true
